
CREATE TABLE STUDENT (
  ID VARCHAR2(55) PRIMARY KEY,
  NAME VARCHAR2(255) ,
  AGE INTEGER   
);

CREATE TABLE MAIL (
  ID VARCHAR2(55) PRIMARY KEY, 
  TITLE VARCHAR2(2048),
  CONTENT VARCHAR2(2048) ,
  SEND_ID INTEGER,
  SEND_DATE DATE
);

CREATE TABLE SYS_USER (
  ID VARCHAR2(55) PRIMARY KEY,
  USER_NAME VARCHAR2 (55),
  REAL_NAME VARCHAR2 (55),
  PASSWORD VARCHAR2 (128),
  DEPT_NAME VARCHAR2 (55),
  MEMBER_ID VARCHAR2 (55)
);

CREATE TABLE CHECKING_IN (
  ID VARCHAR2(55) PRIMARY KEY,
  USER_ID VARCHAR2(55),
  HOUR INTEGER,
  START_DATE date,
  END_DATE date,
  "MONTH" INTEGER,
  STATUS INTEGER,
  over_time number(12,2)
  
) ;

CREATE TABLE CHECKING_IN_RECORD (
  ID VARCHAR2(55) PRIMARY KEY,
  USER_ID VARCHAR2(55),
  CHECKING_IN_DATE date,
  MONTH INTEGER
) ;

/*DROP TABLE  STUDENT;
DROP TABLE  MAIL;
DROP TABLE  SYS_USER;
DROP TABLE  CHECKING_IN;
DROP TABLE  CHECKING_IN_RECORD;*/

SELECT * FROM STUDENT;
SELECT * FROM MAIL;
SELECT * FROM SYS_USER;
SELECT * FROM CHECKING_IN;
SELECT * FROM CHECKING_IN_RECORD;